name: Verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install C dev dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y \
            libcyaml-dev libyaml-dev \
            libipmimonitoring-dev libfreeipmi-dev \
            libmicrohttpd-dev \
            libcmocka-dev \
            cppcheck

      - run: make lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install C dev dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -y \
            libcyaml-dev libyaml-dev \
            libipmimonitoring-dev libfreeipmi-dev \
            libmicrohttpd-dev \
            libcmocka-dev

      - run: make test
